SELECT ID, FISH_NAME, LENGTH FROM FISH_INFO INNER JOIN FISH_NAME_INFO
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS M
ON FISH_INFO.FISH_TYPE = M.FISH_TYPE
AND FISH_INFO.LENGTH = M.MAX_LENGTH
ORDER BY ID