SELECT TITLE, USED_GOODS_BOARD.BOARD_ID, 
REPLY_ID, USED_GOODS_REPLY.WRITER_ID, 
USED_GOODS_REPLY.CONTENTS, 
SUBSTR(USED_GOODS_REPLY.CREATED_DATE, 1, 10)
FROM USED_GOODS_BOARD INNER JOIN USED_GOODS_REPLY 
ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
WHERE USED_GOODS_BOARD.CREATED_DATE LIKE '2022-10%' 
ORDER BY USED_GOODS_REPLY.CREATED_DATE, TITLE